const express = require('express');
const router = express.Router();
const paystackWebhookController = require('./paystackWebhook.controller');

/**
 * @swagger
 * /api/subscriptions/paystack/webhook:
 *   post:
 *     tags: [Subscriptions]
 *     summary: Paystack Webhook Handler (Public)
 *     description: |
 *       Receives transaction status notifications from Paystack.
 *       Verifies the payload signature using the `X-Paystack-Signature` header and `PAYSTACK_SECRET_KEY`.
 *       Processes `charge.success` events to update pending organization onboarding requests or active organization subscriptions.
 *     parameters:
 *       - in: header
 *         name: x-paystack-signature
 *         required: true
 *         schema:
 *           type: string
 *           example: "x_example"
 *         description: HMAC SHA512 signature of the raw request body generated using the Paystack secret API key.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [event, data]
 *             properties:
 *               event:
 *                 type: string
 *                 example: charge.success
 *                 description: The type of event sent by Paystack.
 *               data:
 *                 type: object
 *                 required: [id, status, reference, amount, metadata]
 *                 properties:
 *                   id:
 *                     type: integer
 *                     example: 123456789
 *                     description: Unique transaction ID generated by Paystack.
 *                   status:
 *                     type: string
 *                     example: success
 *                   reference:
 *                     type: string
 *                     example: ref-mock-1718182902345
 *                     description: Unique transaction reference generated during initialization.
 *                   amount:
 *                     type: integer
 *                     example: 9900
 *                     description: Transaction amount in minor units (e.g., Pesewas for GHS).
 *                   metadata:
 *                     type: object
 *                     required: [planId, userId]
 *                     properties:
 *                       requestId:
 *                         type: string
 *                         description: Optional. Onboarding request ID to activate/move to pending status.
 *                         example: req-1234-uuid
 *                       organizationId:
 *                         type: string
 *                         description: Optional. Organization ID to apply subscription upgrade/renewal.
 *                         example: org-5678-uuid
 *                       planId:
 *                         type: string
 *                         example: plan-growth-uuid
 *                       userId:
 *                         type: string
 *                         example: user-9876-uuid
 *                       billingCycle:
 *                         type: string
 *                         enum: [monthly, yearly]
 *                         example: monthly
 *     responses:
 *       200:
 *         description: Event acknowledged and processed successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: success
 *       401:
 *         description: Unauthorized. Missing or invalid signature.
 *       500:
 *         description: Internal server error while processing the event.
 */
router.post('/webhook', paystackWebhookController.handleWebhook);

module.exports = router;
